### ISSUE TITLE
Tweak required for Windows setup.

### ISSUE THREAD

**Issue by ogrotten** [kennethklee/clean-svelte-vite-electron#3]
[This StackOverflow post](https://stackoverflow.com/a/37131308/289296) give instructions on using `NODE_ENV` in a cross-platform way. The end result is a little tricker because of needing to escape the quotes. 

```
  "scripts": {
    ...
    "start": "cross-env NODE_ENV=development concurrently \"npm run web:watch\" \"npm run electron:start\"",
  }
```

Hope this helps.

**Comment by kennethklee** [comment]
that should do it =)
